#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[aliases]

init = ["git", "init"]
push = ["git", "push"]
pull = ["git", "fetch"]
s = ["status"]
move = ["bookmark", "move", "--allow-backwards"]

[user]

name = "roylez"
email = "me@roylez.info"

[ui]
default-command = "log"

[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
pager = "delta"
# NOTE: this is required when using `delta` as a pager
diff-formatter = ":git"
