#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[aliases]

init = ["git", "init"]
push = ["git", "push"]
pull = ["git", "fetch"]
s = ["status"]

[user]

name = "roylez"
email = "me@roylez.info"

[ui]
default-command = "log"

